version: '3.8'

services:
  frontend:
    build:
      context: nuxt-frontend
      dockerfile: Dockerfile
    container_name: getting-started-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  backend:
    build:
      context: ./django_gateway/
      dockerfile: Dockerfile
    container_name: getting-started-backend
    ports:
      - "8000:8000"
    volumes:
      - ./django_gateway:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CORS_ORIGIN_WHITELIST=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
